### ISSUE TITLE
cities field in baggers.js difficult to parse

### ISSUE THREAD

**Issue by Nilhcem** [brownbaglunch/data#110]
The `cities` field changed from being an array of city to a single object containing many cities per field name.
This add some duplication in the cities name, complexifies the parsing, and I can't see any advantages in using this format

Now: 

```
"cities": {
    "Aix-en-Provence": {
      "name": "Aix-en-Provence",
      "ville_img": "img/villes/BBL.jpg",
      "lat": 43.529742,
      "lng": 5.447427
    },
    "Avignon": {
      "name": "Avignon",
      "ville_img": "img/villes/BBL_Avignon.jpg",
      "lat": 43.941557,
      "lng": 4.8332525
    }
}
```

Before:

```
"cities": [
        {
            "name": "Tours",
            "ville_img": "img/villes/BBL_Tours.jpg",
            "lat": 47.396651,
            "lng": 0.694286
        },
        {
            "name": "Paris",
            "ville_img": "img/villes/BBL.jpg",
            "lat": 48.856614,
            "lng": 2.352222
        }
]
```

**Comment by dadoonet** [comment]
It simplifies the access to a given city. Like `cities.Avignon`. `Avignon` is basically like an ID here. The same we can find when a speaker adds a list of cities he can speak in.

I would not change it. We could potentially remove the inner `name` field though as it is a duplicate.
IIRC when I wrote it, I found easier to display it in the web pages.
