### ISSUE TITLE
data are not updated on the website

### ISSUE THREAD

**Issue by dadoonet** [brownbaglunch/data#392]
http://data.brownbaglunch.fr/baggers.js is not published anymore.

For example `Arthur Micoulet` is in one of the latest commits but not present in http://data.brownbaglunch.fr/baggers.js.

**Comment by dadoonet** [comment]
![image](https://user-images.githubusercontent.com/274222/60810243-f0441d80-a18c-11e9-8c8a-582af1d6372c.png)

**Comment by dadoonet** [comment]
I ran Jekyll locally to see if we have any error message but no luck. It worked locally.
Going to see if I can desactivate the website and reactivate again to trigger a new generation.

**Comment by dadoonet** [comment]
Reported at https://github.community/t5/GitHub-Pages/Page-build-failed-how-to-get-the-logs/m-p/27047#M1872

Let's see...

**Comment by kassovix** [comment]
Any news on this ?
Let me know if you need help.

**Comment by dadoonet** [comment]
Sure. I haven't been able to reproduce the issue when building the pages locally.
If you want to try that'd be great.

**Comment by kassovix** [comment]
I can run the Jekyll site from https://github.com/brownbaglunch/BrownBagLunch but couldn't find out how you publish the https://github.com/brownbaglunch/bblfr_data/ to http://data.brownbaglunch.fr/baggers.js

**Comment by kassovix** [comment]
Ok nevermind, Jekyll is running and serving the baggers.js fine on http://localhost/baggers.js. Do not reproduce any problem here...

**Comment by kassovix** [comment]
Maybe you can try to rollback to the last commit successfully published : https://github.com/brownbaglunch/bblfr_data/commit/3738085ebeaf46a42e36b0483a07478554cf6fe9#diff-f68e2795800a6af5bcbab7a5fdb2f2c1
And see if it works with this version...

**Comment by dadoonet** [comment]
It's fixed now. Was most likely caused by a security issue
