### ISSUE TITLE
data is not published anymore

### ISSUE THREAD

**Issue by dadoonet** [brownbaglunch/data#419]
As for #392 http://data.brownbaglunch.fr/baggers.js is not published anymore.

@linsolas could you help?

**Comment by linsolas** [comment]
Toujours la même chose...

<img width="792" alt="image" src="https://user-images.githubusercontent.com/623217/70309112-0e31af00-180d-11ea-9216-bb9b95d39a17.png">

Et toujours aussi peu d'informations sur pourquoi ça ne marche pas 😠 

J'investigue...

**Comment by linsolas** [comment]
Moi avoir pouvoirs magiques.
J'ai fait un pauvre commit de rien du tout (une modification dans la description du `package.json`, c'est dire), et PAF !

<img width="774" alt="image" src="https://user-images.githubusercontent.com/623217/70309368-acbe1000-180d-11ea-8135-9e34c295eee2.png">

Et now, ça worke :

<img width="538" alt="image" src="https://user-images.githubusercontent.com/623217/70309383-b3e51e00-180d-11ea-85f0-8a28fa5ed2cf.png">

**Comment by dadoonet** [comment]
😮 Merci !

**Comment by linsolas** [comment]
OK, j'ai fait un peu d'investigation, je pense que **mergify** est bien la source du problème : https://github.com/vmware/precaution/issues/205#issuecomment-487038721 et surtout https://github.com/vmware/precaution/issues/205#issuecomment-487937613 : 

> GitHub support have informed me that there's a protection mechanism in place that prevents bot users from automatically building GitHub Pages. Upstream are considering what to do with this.

Bref, @dadoonet il va falloir merger nous-mêmes plutôt que de laisser mergify le faire !
