### ISSUE TITLE
baggers data change proposal

### ISSUE THREAD

**Issue by dadoonet** [brownbaglunch/data#65]
As I'm adding some features to the website, I'd like to propose a new format for `baggers`.

Nowadays, we have:

``` json
{
   "name":"BAGGER NAME",
   "bio":"BIO",
   "picture":"Link to picture",
   "websites":[
      {
         "title":"Blog",
         "href":"LINK"
      },
      {
         "title":"GitHub",
         "href":"LINK"
      }
   ],
   "twitter":"ACCOUNT",
   "contact":"EMAIL",
   "mail":"EMAIL",
   "location":"CITY NAME",
   "sessions":[
      {
         "title":"TITLE",
         "summary":"ABSTRACT"
      }
   ],
   "tags":[
      "TAG",
      "TAG"
   ],
   "cities":[
      "CITY NAME",
      "CITY NAME"
   ]
}
```

Change proposal:

``` json
{
   "created":"DATE OF CREATION",
   "name":"BAGGER NAME",
   "bio":"BIO with support for HTML / Markdown",
   "picture":"Link to picture",
   "websites":[
      {
         "title":"Blog",
         "href":"LINK"
      },
      {
         "title":"GitHub",
         "href":"LINK"
      }
   ],
   "twitter":"ACCOUNT",
   "mail":"EMAIL",
   "location":"CITY NAME",
   "sessions":[
      {
         "title":"TITLE",
         "summary":"ABSTRACT",
         "tags":[
            "TAG",
            "TAG"
         ]
      }
   ],
   "cities":[
      {
         "city":"CITY NAME",
         "range":"30km"
      },
      {
         "city":"CITY NAME",
         "range":"30km"
      }
   ]
}
```

Main changes:
- Remove `contact` as we have the same information in `mail`
- Add `created` so we can have a section with the new comers and also provide stats per year
- Move `tags` in `sessions` so users will be able to choose a talk by a `tag`
- `cities` now gives from which city a speaker can talk and up to which distance. It will help to propose talks based on geo loc. 

Thoughts?

**Comment by fsarradin** [comment]
- `created` => `since` or `bagger_since`
- tags in session => ok
- cities + range => ok
- duplication between contact and email => you'll have to wait for second answer as I'm on a phone ^^

**Comment by dadoonet** [comment]
@fsarradin Thanks for the first comments so far. I agree about `since`.

About duplication, I know that for historical reason, we had both but as far as I can see now we are not publishing anymore the `mail` but using `contact` in our contact form.

**Comment by fsarradin** [comment]
@dadoonet there some people that prefers to be contacted by twitter instead of mail. As an example, take a look at "mathieubolla" who has no mail.

There's also some people who doesn't have the same value between `contact` and `mail` because `contact` is displayed. This isn't the case for `mail`, which is used to send mail to baggers.

**Comment by dadoonet** [comment]
@fsarradin I just looked at http://www.brownbaglunch.fr/baggers.html and I was not able to see any `contact` displayed. Are you sure that we are still using it? That was my initial concern.

I think we should:
- keep only `mail` 
- if `mail` is empty, instead of displaying the contact form, open twitter and create a new tweet like `Hi @[TWITTER_VALUE]! I'd like to invite you for a @bbl_fr talk.` or something along those lines.

Thoughts?

**Comment by fsarradin** [comment]
@dadoonet you've got the point about the usage of `contact`. Your solution is one possibility. On the other hand, I propose to remove `mail` and use `contact` with this URN pattern:
- `mailto:email@ddr.ess`
- `tweetto:@twitteraccount`
- `whatever:...`

Thoughts (your turn ;) )?

**Comment by dadoonet** [comment]
I don't like having to parse the string TBH. 

We could split the contact as:

``` json
"contact": {
   "type": "mail",
   "url": "email@ddr.ess"
}
```

``` json
"contact": {
   "type": "twitter",
   "url": "twitteraccount"
}
```

With `type` by default equal to `mail` so people can write:

``` json
"contact": {
   "url": "email@ddr.ess"
}
```

But it makes the structure more complicated...

Unsure... Your turn? :D 

May be others could comment ??? @linsolas WDYT?

**Comment by dadoonet** [comment]
Closing as changed have been merged now...
