### ISSUE TITLE
Demande en erreur

### ISSUE THREAD

**Issue by yannickameur** [brownbaglunch/data#68]
Bonjour
J'ai une barre rouge after clic demande 
![bug demande bbl](https://cloud.githubusercontent.com/assets/249853/12514809/7b3c9012-c125-11e5-8d9e-7e9256a63581.PNG)

**Comment by dadoonet** [comment]
En attendant qu'on corrige, tu peux m'envoyer un mail à david at elastic.co ? :D

**Comment by nrichand** [comment]
Hum, visiblement c'est l'appli qui envoie les mails qui est down. Je
regarde.

On Fri, Jan 22, 2016 at 4:31 PM, David Pilato notifications@github.com
wrote:

> En attendant qu'on corrige, tu peux m'envoyer un mail à david at
> elastic.co ? :D
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/brownbaglunch/bblfr_data/issues/68#issuecomment-173951678
> .

## 

_Nathaniel Richand_

Email : nrichand@gmail.com

Mobile : +33(0)6 18 09 84 25

LinkedIn : www.linkedin.com/in/nrichand

**Comment by yannickameur** [comment]
PS y a pas de message ...

Yannick AMEUR

Le 22 janvier 2016 à 16:33, Nathaniel Richand notifications@github.com a
écrit :

**Comment by dadoonet** [comment]
@nrichand C'est corrigé ? On peut fermer cette issue ?

**Comment by nrichand** [comment]
Oui, bien vu!
